version: '3.10.11'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://todolist_user:1234@db:5432/tododb

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todolist_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tododb


volumes:
  postgres_data:
