"""Initial database setup

Revision ID: 80dfa93e8d31
Revises: 
Create Date: 2024-03-12 02:49:24.588999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dfa93e8d31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_lists_id'), 'todo_lists', ['id'], unique=False)
    op.create_index(op.f('ix_todo_lists_name'), 'todo_lists', ['name'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['todo_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.create_index(op.f('ix_todo_items_title'), 'todo_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_items_title'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_todo_lists_name'), table_name='todo_lists')
    op.drop_index(op.f('ix_todo_lists_id'), table_name='todo_lists')
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
